
site_name: 'ThousandEyes - Splunk Integrations Workshop'
site_description: ThousandEyes - Splunk Integrations Workshop
site_author: Antonio Jimenez

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Home: README.md
  - Getting Started:
    - Access Postman: getting_started/access_postman.md
    - Login ThousandEyes: getting_started/login_thousandeyes.md
    - Create ThousandEyes test: getting_started/create_thousandeyes_test.md
  - Splunk Observability Cloud:
    - Login Splunk Observability Cloud: splunk_observability/login_splunk_observability.md
    - Create Streams to Splunk Observability Cloud: splunk_observability/create_streams_to_splunk_observability.md
    - Visualize ThousandEyes data in Splunk Observability Cloud: splunk_observability/visualize_splunk_observability.md
  - Splunk Cloud / Enterprise:
    - Login Splunk Cloud / Enterprise: splunk_core/login_splunk_cloud_enterprise.md
    - Create Streams to Splunk Cloud / Enterprise: splunk_core/create_streams_to_splunk_cloud_enterprise.md
    - Visualize ThousandEyes data in Splunk Cloud / Enterprise: splunk_core/visualize_splunk_cloud_enterprise.md
  - Cisco ThousandEyes App for Splunk: cisco_thousandeyes_app_for_splunk.md
  - Distributed Tracing - Service Map: distributed_tracing_service_map.md

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime


markdown_extensions:
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true


copyright: |
  &copy; 2025 <a href="https://cisco.com"  target="_blank" rel="noopener">Cisco Systems, Inc.</a>
